services:
  KPO4:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: KPO4
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d KPO4" ]
      interval: 5s
      timeout: 5s
      retries: 5
      #volumes:
      #- pgdata:/var/lib/postgresql/data
  paymentsservice:
    image: paymentsservice
    build:
      context: .
      dockerfile: PaymentsService/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      KPO4:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development